---
title: '"R" It My Mistress (sales forecasting)'
output: html_document
date: "2023-04-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(fable) # forecasting package
library(lubridate)
library(plotly)
library(rsample)
library(tsibble)
library(RSQLite)
library(scales)
```

## Import data from SQLite3 database

```{r}
rm(list=ls())
db <- dbConnect(SQLite(), dbname="/Users/Owner/Documents/GitHub/RIMBOUKARI/commodity_trade.sqlite3")
```
```{r}
sales <- dbGetQuery(db,"SELECT flow,trade_usd FROM commodity;")
```
```{r}
sales %>% count(flow) %>% ggplot(aes(x=flow,y=n)) +
  geom_col() + labs(title="Row Count by Flow") +
  scale_y_continuous(label = comma)
```

```{r}
sales %>% group_by(flow) |> 
  summarise(total = sum(trade_usd)) |>
  ggplot(aes(x=flow,y=total)) + geom_col() +
  labs(title="Toal Sales(USD) by Flow") +
  scale_y_continuous(label = comma)
```

### Create repeating yearly date series

Use R/tidyverse/lubridate to create a yearly date series (YYYY-MM-DD) beginning with 2010 and ending with 2020 and repeating the data series till the end of the data frame. 

```{r}
imports <- sales %>% filter(flow =="Import")
exports <- sales %>% filter(flow =="Export")

```

#### Create yearly date seq for exports

```{r}
set.seed(9999)
start_date <- as.Date("2000-01-01")
end_date <- as.Date("2020-12-31")
n_rows <- nrow(exports)
yearly_seq <- seq(start_date, end_date, length.out = n_rows)

exports$yearly_date <- yearly_seq
exports$yearly_date <- as.character(exports$yearly_date)
dbWriteTable(db,"exports",exports,overwrite =TRUE)
exports$yearly_date <- as.Date(exports$yearly_date)
```

## Plot Row counts based on the yearly_date column
#### Begin Analysis of Exports

```{r}
exports_daily <- dbGetQuery(db,"SELECT * FROM exports_daily;")
exports_daily$yearly_date <-ymd(exports_daily$yearly_date)

```
```{r}
summary(exports_daily)
            
```

```{r}
exports_daily |> filter(yearly_date !="2020-12-31") %>%
ggplot() + geom_col(aes(x=yearly_date,y=total_sales))
```



